---
title: "Day 4 Comp Session 4"
format: html
editor: visual
---

## Create vectors

```{r}
rain <- c(3,5,10.1,6)

rain_scaled <- 5 * rain
```

## Create matrices

```{r}
# create sequence of values
my_values <- seq(from = 1, to = 10)

# create matrix 
my_matrix <- matrix(data = my_values, nrow = 2, ncol = 5, byrow = TRUE)

# another matrix
my_matrix2 <- matrix(data = my_values, nrow = 3, ncol = 4, byrow = TRUE)

# matrix but make sequence within the argument
matrix_a <- matrix(data = seq(from = 2, to = 5, length = 10), 
                   nrow = 2, 
                   ncol = 5, 
                   byrow = TRUE)
```

```{r}
# addition and subtraction
my_matrix + matrix_a
my_matrix - matrix_a
```

## Matrix multiplication

```{r}
# create matrices 
cats <- matrix(data = c(0, 4, 1, 7), nrow = 2, ncol = 2, byrow = TRUE)
dogs <- matrix(data = c(3, 5, 8, 4), nrow = 2, ncol = 2, byrow = TRUE)

# multipy the matrices
dogs %*% cats
```

## Leslie matrix example

```{r}
insect_leslie <- matrix(data = c(0, 0, 600, 0.2, 0, 0, 0, 0.08, 0), 
                        nrow = 3, 
                        ncol = 3, 
                        byrow = TRUE)

# initial values
insect_y0 <- c(12000, 700, 500)
```

Find the population structure for each life stage at t=1 year:

```{r}
insect_y1 <- insect_leslie %*% insect_y0
```

Find the population structure for each life stage at t = 2 years:

```{r}
insect_y2 <- insect_leslie %*% insect_y1
```
